// ✅ src/services/firebase/userService.js

import { db } from "@/config/firebase";
import {
  doc,
  getDoc,
  getDocs,
  setDoc,
  updateDoc,
  collection,
  onSnapshot,
  serverTimestamp,
  deleteDoc,
  query,
  where,
} from "firebase/firestore";

// --- User CRUD Operations ---
export const setUser = async (uid, data) => {
  await setDoc(doc(db, "users", uid), { ...data });
};

export const getUser = async (uid) => {
  const userRef = doc(db, "users", uid);
  const snapshot = await getDoc(userRef);
  if (snapshot.exists()) {
    const userData = { id: snapshot.id, ...snapshot.data() };
    if (userData.createdAt && typeof userData.createdAt.toDate === "function") {
      userData.createdAt = userData.createdAt.toDate().toISOString();
    }
    return userData;
  }
  return "User not found";
};

// Get user by username
export const getUserByUsername = async (username) => {
  if (!username) return "Username is required";

  const normalized = username.toLowerCase().trim();
  const q = query(collection(db, "users"), where("username", "==", normalized));
  const snapshot = await getDocs(q);

  if (!snapshot.empty) {
    const userData = { id: snapshot.docs[0].id, ...snapshot.docs[0].data() };
    if (userData.createdAt && typeof userData.createdAt.toDate === "function") {
      userData.createdAt = userData.createdAt.toDate().toISOString();
    }
    return userData;
  }
  return "User not found";
};

export const updateUser = async (uid, data) => {
  await updateDoc(doc(db, "users", uid), data);
};

export const deleteUser = async (uid) => {
  await deleteDoc(doc(db, "users", uid));
  return { id: uid };
};

export const getAllUsers = async () => {
  const snapshot = await getDocs(collection(db, "users"));
  return snapshot.docs.map((doc) => {
    const data = doc.data();

    // Helper function to convert Timestamp to ISO string
    const convertTimestamp = (timestamp) => {
      if (timestamp?.toDate && typeof timestamp.toDate === "function") {
        return timestamp.toDate().toISOString();
      } else if (timestamp?.seconds) {
        // Handle Timestamp objects without toDate method
        return new Date(timestamp.seconds * 1000).toISOString();
      } else if (typeof timestamp === "string") {
        return timestamp;
      }
      return timestamp;
    };

    // Convert all timestamp fields
    const cleanData = {
      id: doc.id,
      ...data,
      createdAt: convertTimestamp(data.createdAt),
      updatedAt: convertTimestamp(data.updatedAt),
      adminActionDate: convertTimestamp(data.adminActionDate),
      fcmTokenUpdatedAt: convertTimestamp(data.fcmTokenUpdatedAt),
    };

    return cleanData;
  });
};

export const subscribeToUsers = (callback) => {
  return onSnapshot(collection(db, "users"), (snapshot) => {
    const users = snapshot.docs.map((doc) => {
      const data = doc.data();

      // Helper function to convert Timestamp to ISO string
      const convertTimestamp = (timestamp) => {
        if (timestamp?.toDate && typeof timestamp.toDate === "function") {
          return timestamp.toDate().toISOString();
        } else if (timestamp?.seconds) {
          // Handle Timestamp objects without toDate method
          return new Date(timestamp.seconds * 1000).toISOString();
        } else if (typeof timestamp === "string") {
          return timestamp;
        }
        return timestamp;
      };

      // Convert all timestamp fields
      const cleanData = {
        id: doc.id,
        ...data,
        createdAt: convertTimestamp(data.createdAt),
        updatedAt: convertTimestamp(data.updatedAt),
        adminActionDate: convertTimestamp(data.adminActionDate),
        fcmTokenUpdatedAt: convertTimestamp(data.fcmTokenUpdatedAt),
      };

      return cleanData;
    });
    callback(users);
  });
};

// --- Company Account Logic ---
export const setCompany = async (email, data) => {
  await setDoc(doc(db, "companyAccount", email), {
    ...data,
    createdAt: serverTimestamp(),
    verificationStatus: "Pending",
    rating: 0,
    reviews: 0,
    stats: { activeJobs: 0, totalHires: 0, successRate: "0%" },
    specializations: [],
  });
};

export const getCompany = async (email) => {
  const companyRef = doc(db, "companyAccount", email);
  const snapshot = await getDoc(companyRef);
  if (snapshot.exists()) {
    const companyData = { id: snapshot.id, ...snapshot.data() };
    if (
      companyData.createdAt &&
      typeof companyData.createdAt.toDate === "function"
    ) {
      companyData.createdAt = companyData.createdAt.toDate().toISOString();
    }
    return companyData;
  }
  return "Company not found";
};

// --- Username Reservation ---
const RESERVED_WORDS = [
  "admin",
  "administrator",
  "support",
  "help",
  "info",
  "contact",
  "login",
  "logout",
  "register",
  "signup",
  "signin",
  "api",
  "dashboard",
  "profile",
  "settings",
  "account",
  "user",
  "users",
  "system",
  "root",
  "test",
  "demo",
  "example",
  "sample",
  "guest",
  "anonymous",
  "public",
  "private",
  "internal",
  "external",
  "official",
  "verified",
  "premium",
  "pro",
  "basic",
  "free",
  "paid",
  "beta",
  "alpha",
  "dev",
  "development",
  "staging",
  "production",
  "live",
  "www",
  "mail",
  "email",
  "webmaster",
  "postmaster",
  "hostmaster",
  "noreply",
  "no-reply",
  "donotreply",
  "do-not-reply",
  "spam",
  "junk",
  "trash",
  "bin",
  "tmp",
  "temp",
  "cache",
  "backup",
  "old",
  "new",
  "current",
  "latest",
  "v1",
  "v2",
  "version",
  "update",
  "upgrade",
  "install",
  "setup",
  "config",
  "configuration",
  "data",
  "database",
  "db",
  "sql",
  "mysql",
  "postgres",
  "mongodb",
  "redis",
  "server",
  "client",
  "app",
  "application",
  "mobile",
  "desktop",
  "web",
  "site",
  "website",
  "blog",
  "forum",
  "chat",
  "message",
  "notification",
  "alert",
  "warning",
  "error",
  "success",
  "info",
  "debug",
  "log",
  "logs",
  "report",
  "reports",
  "analytics",
  "stats",
  "statistics",
  "metrics",
  "monitoring",
  "health",
  "status",
  "ping",
  "pong",
  "echo",
  "test",
  "testing",
  "qa",
  "quality",
  "assurance",
  "security",
  "auth",
  "authentication",
  "authorization",
  "permission",
  "role",
  "roles",
  "group",
  "groups",
  "team",
  "teams",
  "organization",
  "org",
  "company",
  "business",
  "corporate",
  "enterprise",
  "startup",
  "freelancer",
  "mentor",
  "student",
  "teacher",
  "instructor",
  "coach",
  "trainer",
  "consultant",
  "advisor",
  "expert",
  "specialist",
  "professional",
  "developer",
  "programmer",
  "coder",
  "engineer",
  "architect",
  "designer",
  "manager",
  "director",
  "executive",
  "ceo",
  "cto",
  "cfo",
  "vp",
  "head",
  "lead",
  "senior",
  "junior",
  "intern",
  "trainee",
  "apprentice",
  "assistant",
  "helper",
  "support",
  "customer",
  "client",
  "user",
  "member",
  "subscriber",
  "follower",
  "fan",
  "friend",
  "family",
  "personal",
  "private",
  "public",
  "official",
  "unofficial",
  "verified",
  "unverified",
  "confirmed",
  "pending",
  "approved",
  "rejected",
  "suspended",
  "banned",
  "blocked",
  "restricted",
  "limited",
  "unlimited",
  "infinite",
  "finite",
  "bounded",
  "unbounded",
  "complete",
  "incomplete",
  "finished",
  "unfinished",
  "done",
  "undone",
  "ready",
  "not-ready",
  "prepared",
  "unprepared",
  "set",
  "unset",
  "configured",
  "unconfigured",
  "initialized",
  "uninitialized",
  "loaded",
  "unloaded",
  "mounted",
  "unmounted",
  "connected",
  "disconnected",
  "linked",
  "unlinked",
  "bound",
  "unbound",
  "attached",
  "detached",
  "joined",
  "separated",
  "merged",
  "split",
  "divided",
  "multiplied",
  "added",
  "subtracted",
  "increased",
  "decreased",
  "expanded",
  "contracted",
  "grown",
  "shrunk",
  "developed",
  "undeveloped",
  "mature",
  "immature",
  "adult",
  "child",
  "young",
  "old",
  "new",
  "fresh",
  "stale",
  "clean",
  "dirty",
  "pure",
  "impure",
  "clear",
  "unclear",
  "obvious",
  "obscure",
  "visible",
  "invisible",
  "transparent",
  "opaque",
  "solid",
  "liquid",
  "gas",
  "plasma",
  "matter",
  "energy",
  "force",
  "power",
  "strength",
  "weakness",
  "ability",
  "skill",
  "talent",
  "gift",
  "trait",
  "characteristic",
  "feature",
  "property",
  "attribute",
  "quality",
  "aspect",
  "dimension",
  "factor",
  "element",
  "component",
  "part",
  "piece",
  "section",
  "segment",
  "portion",
  "fraction",
  "percentage",
  "ratio",
  "proportion",
  "rate",
  "speed",
  "velocity",
  "acceleration",
  "momentum",
  "force",
  "pressure",
  "tension",
  "stress",
  "strain",
  "load",
  "weight",
  "mass",
  "volume",
  "density",
  "thickness",
  "length",
  "width",
  "height",
  "depth",
  "breadth",
  "extent",
  "scope",
  "range",
  "span",
  "reach",
  "distance",
  "space",
  "area",
  "surface",
  "plane",
  "line",
  "point",
  "dot",
  "spot",
  "mark",
  "sign",
  "symbol",
  "icon",
  "image",
  "picture",
  "photo",
  "photograph",
  "snapshot",
  "screenshot",
  "capture",
  "record",
  "document",
  "file",
  "data",
  "information",
  "knowledge",
  "wisdom",
  "intelligence",
  "smart",
  "clever",
  "brilliant",
  "genius",
  "expert",
  "specialist",
  "professional",
  "master",
  "guru",
  "wizard",
  "ninja",
  "rockstar",
  "superstar",
  "celebrity",
  "famous",
  "popular",
  "trending",
  "viral",
  "hot",
  "cool",
  "awesome",
  "amazing",
  "incredible",
  "fantastic",
  "wonderful",
  "excellent",
  "perfect",
  "ideal",
  "optimal",
  "best",
  "worst",
  "better",
  "worse",
  "good",
  "bad",
  "nice",
  "mean",
  "kind",
  "cruel",
  "gentle",
  "rough",
  "smooth",
  "soft",
  "hard",
  "easy",
  "difficult",
  "simple",
  "complex",
  "basic",
  "advanced",
  "beginner",
  "intermediate",
  "expert",
  "novice",
  "amateur",
  "professional",
  "casual",
  "serious",
  "formal",
  "informal",
  "official",
  "unofficial",
  "public",
  "private",
  "personal",
  "impersonal",
  "direct",
  "indirect",
  "straight",
  "curved",
  "bent",
  "twisted",
  "wrapped",
  "folded",
  "unfolded",
  "opened",
  "closed",
  "shut",
  "locked",
  "unlocked",
  "secure",
  "insecure",
  "safe",
  "unsafe",
  "dangerous",
  "risky",
  "hazardous",
  "harmful",
  "beneficial",
  "helpful",
  "useful",
  "useless",
  "valuable",
  "worthless",
  "expensive",
  "cheap",
  "costly",
  "affordable",
  "reasonable",
  "unreasonable",
  "fair",
  "unfair",
  "just",
  "unjust",
  "right",
  "wrong",
  "correct",
  "incorrect",
  "true",
  "false",
  "real",
  "fake",
  "genuine",
  "authentic",
  "original",
  "copy",
  "duplicate",
  "replica",
  "imitation",
  "fake",
  "counterfeit",
  "forged",
  "fabricated",
  "manufactured",
  "produced",
  "created",
  "made",
  "built",
  "constructed",
  "assembled",
  "installed",
  "setup",
  "configured",
  "initialized",
  "started",
  "launched",
  "opened",
  "begun",
  "commenced",
  "initiated",
  "triggered",
  "activated",
  "enabled",
  "turned-on",
  "switched-on",
  "powered-on",
  "booted",
  "loaded",
  "mounted",
  "connected",
  "linked",
  "joined",
  "attached",
  "bound",
  "tied",
  "fastened",
  "secured",
  "locked",
  "sealed",
  "closed",
  "shut",
  "blocked",
  "barred",
  "prevented",
  "stopped",
  "halted",
  "paused",
  "suspended",
  "interrupted",
  "broken",
  "damaged",
  "destroyed",
  "ruined",
  "wrecked",
  "smashed",
  "crushed",
  "shattered",
  "exploded",
  "imploded",
  "collapsed",
  "fell",
  "dropped",
  "descended",
  "sank",
  "drowned",
  "flooded",
  "soaked",
  "wet",
  "dry",
  "moist",
  "damp",
  "humid",
  "arid",
  "desert",
  "ocean",
  "sea",
  "lake",
  "river",
  "stream",
  "creek",
  "brook",
  "pond",
  "pool",
  "swamp",
  "marsh",
  "bog",
  "moor",
  "heath",
  "meadow",
  "field",
  "farm",
  "garden",
  "park",
  "forest",
  "woods",
  "jungle",
  "savanna",
  "grassland",
  "prairie",
  "steppe",
  "tundra",
  "taiga",
  "alpine",
  "mountain",
  "hill",
  "valley",
  "canyon",
  "gorge",
  "cliff",
  "bluff",
  "ridge",
  "peak",
  "summit",
  "crest",
  "top",
  "bottom",
  "base",
  "foundation",
  "ground",
  "earth",
  "soil",
  "dirt",
  "mud",
  "clay",
  "sand",
  "gravel",
  "stone",
  "rock",
  "boulder",
  "pebble",
  "crystal",
  "gem",
  "jewel",
  "diamond",
  "ruby",
  "emerald",
  "sapphire",
  "pearl",
  "gold",
  "silver",
  "bronze",
  "copper",
  "iron",
  "steel",
  "aluminum",
  "titanium",
  "platinum",
  "palladium",
  "rhodium",
  "iridium",
  "osmium",
  "ruthenium",
  "rhenium",
  "tungsten",
  "molybdenum",
  "niobium",
  "tantalum",
  "vanadium",
  "chromium",
  "manganese",
  "cobalt",
  "nickel",
  "zinc",
  "cadmium",
  "mercury",
  "lead",
  "tin",
  "bismuth",
  "antimony",
  "arsenic",
  "selenium",
  "tellurium",
  "polonium",
  "astatine",
  "radon",
  "francium",
  "radium",
  "actinium",
  "thorium",
  "protactinium",
  "uranium",
  "neptunium",
  "plutonium",
  "americium",
  "curium",
  "berkelium",
  "californium",
  "einsteinium",
  "fermium",
  "mendelevium",
  "nobelium",
  "lawrencium",
  "rutherfordium",
  "dubnium",
  "seaborgium",
  "bohrium",
  "hassium",
  "meitnerium",
  "darmstadtium",
  "roentgenium",
  "copernicium",
  "nihonium",
  "flerovium",
  "moscovium",
  "livermorium",
  "tennessine",
  "oganesson",
  "hydrogen",
  "helium",
  "lithium",
  "beryllium",
  "boron",
  "carbon",
  "nitrogen",
  "oxygen",
  "fluorine",
  "neon",
  "sodium",
  "magnesium",
  "aluminum",
  "silicon",
  "phosphorus",
  "sulfur",
  "chlorine",
  "argon",
  "potassium",
  "calcium",
  "scandium",
  "titanium",
  "vanadium",
  "chromium",
  "manganese",
  "iron",
  "cobalt",
  "nickel",
  "copper",
  "zinc",
  "gallium",
  "germanium",
  "arsenic",
  "selenium",
  "bromine",
  "krypton",
  "rubidium",
  "strontium",
  "yttrium",
  "zirconium",
  "niobium",
  "molybdenum",
  "technetium",
  "ruthenium",
  "rhodium",
  "palladium",
  "silver",
  "cadmium",
  "indium",
  "tin",
  "antimony",
  "tellurium",
  "iodine",
  "xenon",
  "cesium",
  "barium",
  "lanthanum",
  "cerium",
  "praseodymium",
  "neodymium",
  "promethium",
  "samarium",
  "europium",
  "gadolinium",
  "terbium",
  "dysprosium",
  "holmium",
  "erbium",
  "thulium",
  "ytterbium",
  "lutetium",
  "hafnium",
  "tantalum",
  "tungsten",
  "rhenium",
  "osmium",
  "iridium",
  "platinum",
  "gold",
  "mercury",
  "thallium",
  "lead",
  "bismuth",
  "polonium",
  "astatine",
  "radon",
  "francium",
  "radium",
  "actinium",
  "thorium",
  "protactinium",
  "uranium",
  "neptunium",
  "plutonium",
  "americium",
  "curium",
  "berkelium",
  "californium",
  "einsteinium",
  "fermium",
  "mendelevium",
  "nobelium",
  "lawrencium",
  "rutherfordium",
  "dubnium",
  "seaborgium",
  "bohrium",
  "hassium",
  "meitnerium",
  "darmstadtium",
  "roentgenium",
  "copernicium",
  "nihonium",
  "flerovium",
  "moscovium",
  "livermorium",
  "tennessine",
  "oganesson",
];

const normalizeUsername = (username) =>
  (username || "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9._]/g, "")
    .slice(0, 20);

export const isUsernameAvailable = async (username) => {
  const normalized = normalizeUsername(username);
  if (!/^[a-z0-9._]{3,20}$/.test(normalized)) return false;

  // Check if username is in reserved words list
  if (RESERVED_WORDS.includes(normalized)) return false;

  // Check if username already exists in users collection
  const q = query(collection(db, "users"), where("username", "==", normalized));
  const snapshot = await getDocs(q);
  return snapshot.empty;
};

export const createUserDocWithUsername = async (uid, data, username) => {
  const normalized = normalizeUsername(username);
  if (!/^[a-z0-9._]{3,20}$/.test(normalized)) {
    const err = new Error("Invalid username format");
    err.code = "USERNAME_INVALID";
    throw err;
  }

  // Check if username is reserved
  if (RESERVED_WORDS.includes(normalized)) {
    const err = new Error("Username is reserved and cannot be used");
    err.code = "USERNAME_RESERVED";
    throw err;
  }

  // Check if username is already taken
  const isAvailable = await isUsernameAvailable(normalized);
  if (!isAvailable) {
    const err = new Error("Username already taken");
    err.code = "USERNAME_TAKEN";
    throw err;
  }

  // Create user document with username
  await setDoc(doc(db, "users", uid), {
    ...data,
    username: normalized,
    createdAt: data?.createdAt || new Date().toISOString(),
  });

  return normalized;
};
