import NextProvider from "@/components/providers/nextProvider";
import { UsersProvider } from "@/context/usersContext";
import { AuthProvider } from "@/context/AuthContext";
// import { getAllUsers, getUser } from "@/services/firebase";
import { authOptions } from "@/lib/nextAuth";
import { getServerSession } from "next-auth";
import { UserProvider } from "@/context/userContext";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import LayoutWrapper from "@/components/componentts/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased debug-screens`}
        cz-shortcut-listen="true"
        data-gr-ext-installed=""
        data-new-gr-c-s-check-loaded="14.1246.0"
      >
        <Toaster />
        <NextProvider>
          <UserProvider>
            <UsersProvider>
              <LayoutWrapper>{children}</LayoutWrapper>
            </UsersProvider>
          </UserProvider>
        </NextProvider>
      </body>
    </html>
  );
}
