import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NextProvider from "@/components/providers/nextProvider";
import { UsersProvider } from "@/context/usersContext";
import { getAllUsers } from "@/services/firebase";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const users = await getAllUsers();
  console.log(users);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased debug-screens`}
        cz-shortcut-listen="true"
        data-gr-ext-installed=""
        data-new-gr-c-s-check-loaded="14.1243.0"
      >
        <Toaster />
        <NextProvider>
          <UsersProvider initialUsers={users}>{children}</UsersProvider>
        </NextProvider>
      </body>
    </html>
  );
}
