// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { Toaster } from "sonner";
// import NextProvider from "@/components/providers/nextProvider";
// import Footer from "@/components/componentts/Footer";
// import Navbar from "@/components/componentts/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased debug-screens`}
//         cz-shortcut-listen="true"
//         data-gr-ext-installed=""
//         data-new-gr-c-s-check-loaded="14.1243.0"
//       >
//         <Toaster />
//         <NextProvider>
//           <Navbar />
//           {children}
//           <Footer />
//         </NextProvider>
//       </body>
//     </html>
//   );
// }

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import NextProvider from "@/components/providers/nextProvider";
import LayoutWrapper from "@/components/componentts/LayoutWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased debug-screens`}
      >
        <Toaster />
        <NextProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </NextProvider>
      </body>
    </html>
  );
}
